title: "Sarah Dwyer"
author: "Sarah Dwyer"
description: "infra/devops/cs"
permalink: /:title/
lang: "en"

show_footer: false           # show the "previous" and "next" links at the end of each post
dark_theme: true             # use the dark mode as default
dark_header: true            # keep the header dark
dark_footer: true            # keep the footer dark
# style: minimal             # use a simpler style inspired by the minima theme

navigation:                  # site navigation in the header
#  - Twitter: "https://twitter.com/_sdwyer"
#  - Github: "https://github.com/sbd/sbd.github.io"
#  - LinkedIn: "https://www.linkedin.com/in/sbd/"

icons:                      # icons in the header, see http://fontawesome.com/icons
  github: "https://github.com/sbd"
  twitter: "https://twitter.com/_sdwyer"
  linkedin: "https://www.linkedin.com/in/sbd/"
  stack-overflow: "https://stackoverflow.com/users/10177443/dwyer"
#  envelope: "mailto:AAAAAA@users.noreply.github.com"
#  rss: "/contrast/feed.xml"

comments:                    # embed disqus or isso comments
#  disqus: ""
#  isso: ""

plugins:
 - jekyll-feed
 - jekyll-default-layout

theme: jekyll-theme-modernist
