title: "Sarah Dwyer"
author: "Sarah Dwyer"
description: "All things infra and security"
permalink: /:title/
lang: "en"

show_footer: false           # show the "previous" and "next" links at the end of each post
dark_theme: true             # use the dark mode as default
dark_header: true            # keep the header dark
dark_footer: false            # keep the footer dark
style: minimal             # use a simpler style inspired by the minima theme

navigation:                  # site navigation in the header
#  - Twitter: "https://"
#  - Github: "https://"
#  - LinkedIn: "https://"

icons:                      # icons in the header, see https://fontawesome.com/icons
  github: "https://github.com/aradwyr"
  linkedin: "https://www.linkedin.com/in/aradwyr"
  stack-overflow: "https://stackoverflow.com/users/10177443/sarah-dwyer"
#  envelope: "mailto:AAAAAA@users.noreply.github.com"
#  rss: "/contrast/feed.xml"

comments:                    # embed disqus or isso comments
#  disqus: ""
#  isso: ""

plugins:
 - jekyll-feed
 - jekyll-default-layout

theme: jekyll-theme-tactile
