title: "Organized Chaos"
author: "Sarah Dwyer"
description: "infra/devops/cs learnings"
permalink: /:title/
lang: "en"

show_footer: false           # show the "previous" and "next" links at the end of each post
dark_theme: true             # use the dark mode as default
dark_header: true            # keep the header dark
dark_footer: true            # keep the footer dark
# style: minimal             # use a simpler style inspired by the minima theme

navigation:                  # site navigation in the header
  - Twitter: "https://twitter.com/_sdwyer"
  - Github: "https://github.com/sbd/sbd.github.io"

#icons:                      # icons in the header, see http://fontawesome.com/icons
#  envelope: "mailto:niklasbuschmann@users.noreply.github.com"
#  github: "https://github.com/niklasbuschmann/contrast"
#  rss: "/contrast/feed.xml"

comments:                    # embed disqus or isso comments
#  disqus: ""
#  isso: ""

plugins:
 - jekyll-feed
 - jekyll-default-layout

theme: jekyll-theme-modernist